name: math_quiz_app
description: A new Flutter project.
publish_to: 'none'
version: 1.2.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.0
  intl: ^0.20.2
  http: ^1.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.4
  flutter_downloader: ^1.11.3
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  uuid: ^4.2.2
  cached_network_image: ^3.3.0
  window_manager: ^0.3.8
  # 确保这个依赖存在
  flutter_local_notifications: ^20.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true